configs/components/binutils.rb
configs/components/gcc.rb
configs/projects/pl-binutils.rb
configs/projects/pl-gcc.rb

This is the final change I needed to make to pl-build-tools to generate packages which I can then use to build puppet-agent using the u8 solaris 10 template.

Solaris 10 final fixes for u8 template

---

configs/components/binutils.rb
configs/components/yaml-cpp.rb
configs/projects/pl-binutils.rb
configs/projects/pl-boost.rb
configs/projects/pl-gcc.rb
configs/projects/pl-ruby.rb
configs/projects/pl-yaml-cpp.rb

This updates the staging branch on pl-build-tools with relevant updates made to master recently to account for the solaris 10 u8 template issues.

Solaris u8 fixes for pl-build-tools-staging

---

configs/components/gcc.rb
configs/platforms/fedora-f25-i386.rb
configs/platforms/fedora-f25-x86_64.rb
configs/projects/pl-gcc.rb

We're using gcc 6.1 as 4.8.2 doesn't compile cleanly using fedora 25's system gcc, and as a new platform anyway we may as well start with the latest we're aiming to migrate to. Builds pass and generate expected packages.

Fedora 25 platform configs and pl-gcc

---

configs/components/gcc.rb
configs/platforms/ubuntu-16.10-amd64.rb
configs/platforms/ubuntu-16.10-i386.rb
configs/projects/pl-gcc.rb

Like Fedora 25, we're using gcc 6.1.0 since this is a new platform. Build tested and working.

Ubuntu 16.10 platform config and pl-gcc

---

configs/components/boost.rb
resources/patches/boost/no-fionbio.patch

The Cisco IOS XR networking stack doesn't accept `ioctl(fd, FIONBIO,
...)`, which is used by Boost.asio (and eventually pxp-agent). Patch
Boost to use `fnctl`'s `O_NONBLOCK` instead, which should be equivalent.

(BUILD-61) Work-around Cisco IOS XR networking stack bug

---

configs/components/rust.rb
configs/projects/pl-rust.rb

The latest vanagon don't like nil values in environment call value
parameters, this commit aligns the rust component with this expectation.

(maint) Make rust component compatible with latest vanagon

---

configs/components/gettext.rb

Adds fixes for el-4, aix, and Solaris builds. These are essentially
copied from the autoconf component.

(BUILD-41) Support other platforms

---

configs/components/rust.rb

This commit corrects an issue where the Rust 1.16 md5sums for the
tarballs were incorrect.

(maint) Correct md5sums for Rust 1.16 tarballs

---

configs/components/gettext.rb

On EL5, there is a bug in the emacs scripts that gettext tries to
install when it is built. These scripts are used to enable a special
emacs mode for translators editing PO files. Since we don't need that
here at all, this commit disables the emacs addons on all platforms.
I found this solution here: http://lists.busybox.net/pipermail/buildroot/2013-August/076126.html

(BUILD-68) Fix gettext 0.19.8 build on EL5

---

files/cmake/rhel-sles-s390x-toolchain.cmake

Apparently there was some copypasta in here from the powerpc file. I'm pretty sure we're not even using this variable, but I figured I'd fix it. If we want to remove the variable definition completely, that can be a separate PR that would make the change to all the cmake toolchain files where relevant.

(maint) Fix typo in s390x cmake toolchain file

---

Gemfile

Letting this float to master, just as we do for vanagon. I discussed with RelEng and this was the preferred approach instead of pinning the gem to a higher revision.

(maint) Use the latest code from packaging#master

---

configs/components/gcc.rb
configs/components/sysroot.rb
configs/components/toolchain.rb
configs/platforms/el-7-aarch64.rb
configs/projects/pl-build-tools.rb
configs/projects/pl-cmake.rb
configs/projects/pl-gcc.rb
files/cmake/el-aarch64-toolchain.cmake
scripts/generate_el-7-aarch64_sysroot.sh

This patch assumes that the tools will be cross compiled on x86.
It uses machine triple 'aarch64-redhat-linux' as discussed on
https://github.com/puppetlabs/pl-build-tools-vanagon/pull/26
Signed-off-by: Richard Henwood richard.henwood@arm.com

Provide vanagon build tools from CentOS7 or RHELSA on AArch64

---

configs/components/gcc.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb
configs/projects/pl-gcc.rb

This is the set of changes needed to build our pl-build-tools packages for Debian 9 (Stretch) for x86 and x86_64 architectures. 
I've used the packages generated from these changes to successfully build working Debian 9 agents, so this code is tested and is known to work.

Debian 9 (Stretch) Platform Additions

---

configs/projects/pl-binutils.rb
configs/projects/pl-boost.rb
configs/projects/pl-gcc.rb
configs/projects/pl-yaml-cpp.rb

A while back I had mistakenly excluded solaris builds from the cross_compiled check which includes the platform architecture in the package name. This reverts that commit and fixes errors when building the pl-boost package for solaris-11-i386.

Fix Solaris 11 Builds

---

configs/platforms/fedora-f14-i386.rb

When system gcc is provisioned, builds of pl-gettext will link against the
system gcc and cause issues when builds atttempt to only use pl-gcc

(PA-1487) Update fedora-14 build to not provision system gcc

---

configs/components/boost.rb
configs/components/sysroot.rb
resources/patches/boost/boost-aarch64-flags.patch

This builds on previous work from a community contributor who got aarch64 builds working. This just updates the md5sum of the sysroot tarball (which we had to generate ourselves), and fixes a compiler flag compatibility issue in pl-boost.
All of the pl-build-tools packages from this branch have been built and used successfully to build an el-7-aarch64 agent.

Changes to get el-7-aarch64 builds working

---

configs/components/gcc.rb

The location of the configure commands and updates made for AIX are the wrong
way around, so the commands were malformed. This commit fixes that

(PA-1620) Update gcc build to work with AIX

---

configs/components/gcc.rb
configs/platforms/fedora-f27-x86_64.rb
configs/projects/pl-gcc.rb
resources/patches/gcc/sanitizer_linux.patch
resources/patches/gcc/ucontext_t-linux-unwind_h.patch

The reason for the two gcc patches is documented in
configs/components/gcc.rb. The pl-gcc, pl-cmake,
pl-boost, pl-yaml-cpp, and pl-gettext projects were locally
verified to build successfully for Fedora 27, x86_64.

(BUILD-125) Add the Fedora 27 x86_64 platform

---

configs/projects/pl-gcc.rb

Updates the revision of pl-gcc and corrects the gcc version used in
package names for Ubuntu 18.04

(BUILD-150) Correct pl-gcc version name for 18.04

---

Gemfile

This commit adds a Z version to the packaging gem dependency. Previously, older
versions could get pulled in, which don't have necessary updates, like new
platforms, which causes shipping to fail.

(maint) Be more specific with packaging dependency

---

configs/components/gcc.rb
configs/platforms/fedora-28-x86_64.rb
configs/projects/pl-gcc.rb

This is the first Fedora release where we no longer have to include the
'f' in the version field due to improvements in our packaging gem.

(BUILD-141) Add support for Fedora 28

---

configs/components/perl.rb
configs/projects/pl-perl.rb

[Here's an example build of this package](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1/) -- The Windows, AIX, and Solaris 10 builds, plus a few one-off others (ubuntu 16.04 power, for example) don't work, but this project is intended for use specifically with EL 5. I've tested a build of puppet-runtime with a pl-perl package produced by these changes and it seems to configure and build openssl 1.1.0 successfully.

(PA-2107) Add a pl-perl project

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb

- Add the --no-progress switch in an effort to shrink the size of
build logs. Choco describes the feature as:
Do Not Show Progress - Do not show download progress percentages.
Currently, build logs include extremely verbose output when choco
packages are downloading, adding many lines per each 1% of a given
package download. This commit removes that extraneous output.

(maint) Reduce choco build log clutter

---

.travis.yml
Dockerfile
scripts/generate_debian_sysroot.sh
scripts/generate_el-6-s390x_sysroot.sh
scripts/generate_el-7-aarch64_sysroot.sh
scripts/generate_el-7-ppc64le_sysroot.sh
scripts/generate_el-7-s390x_sysroot.sh
scripts/generate_sles-11-s390x_sysroot.sh
scripts/generate_sles-12-ppc64le_sysroot.sh
scripts/generate_sles-12-s390x_sysroot.sh
scripts/generate_ubuntu-16.04-ppc64el_sysroot.sh

By default Travis uses Ubuntu 14.04 to run tests. 
It seems like the libc6-dev package is broken on the debian-sid repository for ubuntu 14.04. libc6-dev is required for shellcheck.
This PR attempts to fix the travis CI job by building a docker image from ubuntu 18.04 and running the shellcheck on that image. 
Travis has no plans to support Ubuntu 16.04 and ubuntu 18.04 in the near future: https://github.com/travis-ci/travis-ci/issues/5821.
This PR also fixes the following errors:
- SC2164 for pushd and popd (https://github.com/koalaman/shellcheck/wiki/SC2164)
- SC2196 https://github.com/koalaman/shellcheck/wiki/SC2196
- $sysroot wrong variable name https://github.com/puppetlabs/pl-build-tools-vanagon/pull/58/commits/53e3c78bd748577279b749f9b78dee693abf735c#diff-0df3d41a6497e3835edd245c3c3 …

Use docker for testing on travis

---

configs/components/cmake.rb
configs/projects/pl-cmake.rb
resources/patches/cmake/use-g++-as-linker-solaris.patch

Reverts puppetlabs/pl-build-tools-vanagon#66
This produced some egregious linking errors during leatherman builds for solaris 11 on SPARC for puppet-agent 5.5.x. It seems like the path of least resistance here is to revert this change, accept the older version of cmake everywhere, and adapt the master branch of puppet-agent to use a more backwards-compatible alternative to `add_compile_definitions`.

Revert "(maint) Update pl-cmake to 3.12.4 for Solaris"

---

Gemfile

Prior to this patch, the Gemfile only allowed VANAGON_LOCATION and
PACKAGING_LOCATION to be sources starting with `git@` or `git:`.
This patch adds `https:` as an option so that repos carrying patches
can be accessed without configuring SSH keys.

Allow Gemfile to use https: sources

---

README.md

Updates the README to explain that this repo is intended only for build
dependencies, and that runtime dependencies should go in the
puppet-runtime project.

(PA-2549) Update README with reference to puppet-runtime

---

ext/build_defaults.yaml

The `gpg_key` setting is overridden by `build-data`. Removing the
local, soon-to-be-expired key from `build_defaults.yaml` for clarity
and cleanliness.

(RE-13434) Remove old GPG key from build_defaults.yaml

---

Dockerfile

Travis CI was failing trying to pull the ubuntu cosmic 18.10 image which is EOL.

(maint) Use focal instead of cosmic

---

Gemfile
README-internal.md
README.md
configs/components/gcc.rb
configs/components/gmp.rb
configs/components/mpc.rb
configs/components/mpfr.rb
configs/platforms/el-7-x86_64.rb
configs/platforms/sles-12-x86_64.rb
configs/projects/pl-gcc.rb

Mostly for the benefit of creating Java 17 for el-7 and sles-12, we
need a GCC compiler >= 5.5

(RE-14662) Create pl-gcc 12.0

---

configs/components/cmake.rb
configs/components/toolchain.rb
configs/projects/pl-cmake.rb
resources/patches/cmake/0001-FindOpenSSL-Tolerate-tabs-in-header-while-parsing-ve.patch
resources/patches/cmake/0002-FindOpenSSL-Do-not-assume-that-the-version-regex-fin.patch
resources/patches/cmake/0003-FindOpenSSL-Detect-OpenSSL-3.0.0.patch
resources/patches/cmake/0004-FindOpenSSL-Fix-OpenSSL-3.0.0-version-extraction.patch

OpenSSL changed their versioning scheme in 3.0, which breaks CMake's FindOpenSSL.
Building https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1975/

(maint) Patch CMake for OpenSSL 3

---

ext/build_defaults.yaml

Delete obsolete build_defaults.yaml setting 'gpg_name'

(maint) delete obsolete 'gpg_name'
